defaults: &defaults

  mimas: 'http://fitark.org'
  block_content: '/block_content/show'
  hospital_code:
    yuquan: '00001'

  aliyunOSS:
      server: 'oss.aliyuncs.com'
      access_key_id: 'h17xgVZatOgQ6IeJ'
      secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
      default_bucket: 'mimas-open'
      video_bucket: 'dev-mimas'
      oss_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'


development:
  <<: *defaults

production:
  block_content: '/block_content/show'
  files_mount: '/dfs/'
  mimas: 'http://www.kanbing365.com'
  hospital_code:
    yuquan: '00001'

  aliyunOSS:
      server: 'oss.aliyuncs.com'
      access_key_id: 'h17xgVZatOgQ6IeJ'
      secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
      default_bucket: 'mimas-open'
      video_bucket: 'webadmin-video'
      oss_url: 'http://webadmin-video.oss-cn-beijing.aliyuncs.com/'