defaults: &defaults

  mimas: 'http://fitark.org'
  block_content: '/block_content/show'
  block_content_list: '/block_content/list'
  hospital_code:
    yuquan: '00001'

  aliyunOSS:
      server: 'oss.aliyuncs.com'
      access_key_id: 'h17xgVZatOgQ6IeJ'
      secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
      photo_buket: 'mimas-open'
      default_bucket: 'dev-mimas'
      oss_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'
      photo_url: 'http://mimas-open.oss-cn-hangzhou.aliyuncs.com/'
      video_bucket: 'dev-mimas'
      video_service: 'oss-cn-beijing.aliyuncs.com'
      video_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'
      kindeditor_bucket: 'dev-mimas'
      kindeditor_service: 'oss-cn-beijing.aliyuncs.com'
      kindeditor_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'
development:
  <<: *defaults

production:
  block_content: '/block_content/show'
  block_content_list: '/block_content/list'
  files_mount: '/dfs/'
  mimas: 'http://www.kanbing365.com'
  hospital_code:
    yuquan: '00001'

  aliyunOSS:
      server: 'oss.aliyuncs.com'
      access_key_id: 'h17xgVZatOgQ6IeJ'
      secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
      photo_buket: 'mimas-open'
      default_bucket: 'mimas-open'
      oss_url: 'http://mimas-open.oss-cn-hangzhou.aliyuncs.com/'
      photo_url: 'http://mimas-open.oss-cn-hangzhou.aliyuncs.com/'
      video_bucket: 'webadmin-video'
      video_service: 'oss-cn-beijing.aliyuncs.com'
      video_url:  'http://webadmin-video.oss-cn-beijing.aliyuncs.com/'
      kindeditor_bucket: 'mimas-open'
      kindeditor_service: 'oss.aliyuncs.com'
      kindeditor_url: 'http://mimas-open.oss-cn-hangzhou.aliyuncs.com/'