defaults: &defaults

  block_content: '/block_content/show'
  block_content_list: '/block_content/list'
  hospital_code:
    yuquan: '00001'
  #  mimas: 'http://admin.kanbing365.com'
  #  mimas: 'http://kanbing365.gre-medical.org'
  mimas: 'http://192.168.1.62:3000'
  #dicom: 'http://www.kanbing365.com:8080/' #dicom 上传/查询--公網
   #aliyunPacs: 'http://dev-pacs.oss-cn-beijing.aliyuncs.com/' #dicom影像数据存放阿里云路径--公網
  dicom: 'http://dev.viicare.com:8090/' #樓下測試地址--測試用的
  aliyunPacs: 'http://test-pacs.oss-cn-beijing.aliyuncs.com/' #dicom影像数据存放阿里云路径--測試用的
  aliyunOSS:
      server: 'oss.aliyuncs.com'
      beijing_service: 'oss-cn-beijing.aliyuncs.com'
      access_key_id: 'h17xgVZatOgQ6IeJ'
      secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
      video_bucket: 'dev-mimas'
      image_bucket: 'dev-mimas'
      video_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'
      image_url:  'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'
      photo_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/avatar/'
      kindeditor_bucket: 'dev-mimas'
      kindeditor_service: 'oss-cn-beijing.aliyuncs.com'
      kindeditor_url: 'http://dev-mimas.oss-cn-beijing.aliyuncs.com/'
  jsdicom: '/dicom/show/'
  aliyunPacs: 'http://dev-pacs.oss-cn-beijing.aliyuncs.com/'
development:
  <<: *defaults

production:
  block_content: '/block_content/show'
  block_content_list: '/block_content/list'
  files_mount: '/dfs/'
  mimas: 'http://admin.kanbing365.com'
  hospital_code:
    yuquan: '00001'
  #  mimas: 'http://kanbing365.gre-medical.org'
  #mimas: 'http://192.168.1.62:3000'
  dicom: 'http://www.kanbing365.com:8080/' #dicom 上传/查询--公網
  aliyunPacs: 'http://dev-pacs.oss-cn-beijing.aliyuncs.com/' #dicom影像数据存放阿里云路径--公網
  #dicom: 'http://dev.viicare.com:8090/' #樓下測試地址--測試用的
  #aliyunPacs: 'http://test-pacs.oss-cn-beijing.aliyuncs.com/' #dicom影像数据存放阿里云路径--測試用的
  aliyunOSS:
      server: 'oss.aliyuncs.com'
      beijing_service: 'oss-cn-beijing.aliyuncs.com'
      access_key_id: 'h17xgVZatOgQ6IeJ'
      secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
      video_bucket: 'mimas-video'
      image_bucket: 'mimas-img'
      video_url:  'http://mimas-video.oss-cn-beijing.aliyuncs.com/'
      image_url:  'http://mimas-img.oss-cn-beijing.aliyuncs.com/'
      photo_url: 'http://mimas-img.oss-cn-beijing.aliyuncs.com/avatar/'
      kindeditor_bucket: 'mimas-img'
      kindeditor_service: 'oss-cn-beijing.aliyuncs.com'
      kindeditor_url: 'http://mimas-img.oss-cn-beijing.aliyuncs.com/'
  jsdicom: '/dicom/show/'
  aliyunPacs: 'http://dev-pacs.oss-cn-beijing.aliyuncs.com/'
