# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cca4cb8013b497895381e346f760c5ef258d1ca14377fb988e0abcf8f082efb3d37c13f1ff8975fb41af20c101759005c96fcf40cde35fff224051b57a80661

test:
  secret_key_base: 682a8f140be8ce750e92b58cd6c6d7fba7cbf847c5f6c7db5761e6054292971e435464f208bfd727ce68b38ae2052455d7cba634fd4f40a958338d154e31c86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
   secret_key_base: 2cca4cb8013b497895381e346f760c5ef258d1ca14377fb988e0abcf8f082efb3d37c13f1ff8975fb41af20c101759005c96fcf40cde35fff224051b57a80661
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
